- name: Install system packages
  apt: name={{ item }} state=installed
  with_items:
    - daemontools # for envdir
    - lzop
    - postgresql
    - pv

- name: Create deploy user
  user: name=deploy

- name: Create folders
  file: path=/opt/keter/{{ item }} state=directory owner=deploy
  with_items:
    - bin
    - etc
    - incoming

- name: Copy keter binary #from S3
  copy: src=keter dest=/opt/keter/bin/keter mode=0700 owner=deploy
  #get_url: url=https://s3.amazonaws.com/keter.jcd/keter dest=/opt/keter/bin/keter mode=0700 owner=deploy

- name: Install config file
  copy: src=keter-config.yml dest=/opt/keter/etc/keter-config.yml

- name: Add upstart job
  copy: src=keter.conf dest=/etc/init/keter.conf
  notify: restart keter

# -- Postgres backups -----
- name: Install S3 backups
  pip: name=s3-backups

- name: Backup cron job
  cron: name="postgres backup" hour=2 job="/usr/local/bin/postgres_to_s3.py --AWS_ACCESS_KEY_ID='{{ aws_access_key_id }}'  --AWS_SECRET_ACCESS_KEY='{{ aws_secret_access_key }}' --S3_BUCKET_NAME='backups.jcd' --S3_KEY_NAME='postgres/{{ ansible_hostname }}' --backup --archive"
