- name: Install packages
  apt: name={{ item }} state=latest
  with_items:
    - rsync

- name: Create media group
  group: name=media state=present

- name: Add me to media group
  user: name=james groups=media append=yes

# -- DOWNLOADS -----
- name: Create data directories
  file: path={{ data_directory }}/{{ item }} state=directory owner=james group=media
  with_items:
    - downloads
    - downloads/.incomplete
    - mirrors
    - music
    - podcasts

# -- TRANSMISSION ----

- name: Make config directory
  file: path=/etc/transmission-daemon state=directory mode=0755

- name: Copy config file
  template: src=transmission-settings.json.j2 dest=/etc/transmission-daemon/settings.json

- name: Install transmission
  apt: name={{ item }} state=latest
  with_items:
    - transmission-cli
    - transmission-common
    - transmission-daemon

# -- BACKUPS ----
- name: Create backup directories
  file: path={{ storage_directory }}/backups state=directory owner=james group=media

# TODO: this should probably be --delete, but check it first!
#- name: Backup server to storage
#  cron: name="server backup" hour=3 minute=1 job="rsync -avz '{{ data_directory }}' '{{ storage_directory }}/backups/{{ ansible_hostname }}'"

